#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PA1.Resource", IsApplication=true)]

namespace PA1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button_background = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int IOtext = 2131099649;
			
			// aapt resource value: 0x7f060011
			public const int answerbutton = 2131099665;
			
			// aapt resource value: 0x7f060002
			public const int clearbutton = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int dividebutton = 2131099653;
			
			// aapt resource value: 0x7f060012
			public const int dotbutton = 2131099666;
			
			// aapt resource value: 0x7f06000f
			public const int eightbutton = 2131099663;
			
			// aapt resource value: 0x7f060014
			public const int equalbutton = 2131099668;
			
			// aapt resource value: 0x7f06000b
			public const int fivebutton = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int fourbutton = 2131099658;
			
			// aapt resource value: 0x7f06000d
			public const int minusbutton = 2131099661;
			
			// aapt resource value: 0x7f060009
			public const int multiplybutton = 2131099657;
			
			// aapt resource value: 0x7f060003
			public const int negatebutton = 2131099651;
			
			// aapt resource value: 0x7f060010
			public const int ninebutton = 2131099664;
			
			// aapt resource value: 0x7f060006
			public const int onebutton = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int plusbutton = 2131099652;
			
			// aapt resource value: 0x7f06000e
			public const int sevenbutton = 2131099662;
			
			// aapt resource value: 0x7f06000c
			public const int sixbutton = 2131099660;
			
			// aapt resource value: 0x7f060000
			public const int tableLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int threebutton = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int twobutton = 2131099655;
			
			// aapt resource value: 0x7f060013
			public const int zerobutton = 2131099667;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
