#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App6.Resource", IsApplication=true)]

namespace App6
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040010
			public const int addition = 2130968592;
			
			// aapt resource value: 0x7f040000
			public const int calculatorAccumulator = 2130968576;
			
			// aapt resource value: 0x7f040012
			public const int clear = 2130968594;
			
			// aapt resource value: 0x7f040005
			public const int div = 2130968581;
			
			// aapt resource value: 0x7f04000e
			public const int dot = 2130968590;
			
			// aapt resource value: 0x7f040003
			public const int eight = 2130968579;
			
			// aapt resource value: 0x7f04000f
			public const int equal = 2130968591;
			
			// aapt resource value: 0x7f040007
			public const int five = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int four = 2130968582;
			
			// aapt resource value: 0x7f040001
			public const int gridLayout1 = 2130968577;
			
			// aapt resource value: 0x7f04000d
			public const int minus = 2130968589;
			
			// aapt resource value: 0x7f040009
			public const int mult = 2130968585;
			
			// aapt resource value: 0x7f040004
			public const int nine = 2130968580;
			
			// aapt resource value: 0x7f04000a
			public const int one = 2130968586;
			
			// aapt resource value: 0x7f040002
			public const int seven = 2130968578;
			
			// aapt resource value: 0x7f040008
			public const int six = 2130968584;
			
			// aapt resource value: 0x7f04000c
			public const int three = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int two = 2130968587;
			
			// aapt resource value: 0x7f040011
			public const int zero = 2130968593;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Main = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
