#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MultiFuncApp.Resource", IsApplication=true)]

namespace MultiFuncApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int cb_color = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int cb_pressedRingWidth = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AddNoiseButton = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int BlueButton = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int GreenButton = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int GreyButton = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int HighContrastButton = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int RedButton = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int rndButton = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070008
			public const int btnRecord = 2131165192;
			
			// aapt resource value: 0x7f070005
			public const int filterFive = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int filterFour = 2131165188;
			
			// aapt resource value: 0x7f070001
			public const int filterOne = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int filterThree = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int filterTwo = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int launchCameraButton = 2131165184;
			
			// aapt resource value: 0x7f070007
			public const int speechText = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int takenPictureImageView = 2131165190;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int messageSpeakNow = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int recordButton = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int textInput = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int button_format = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CircleButton = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int CircleButton_cb_color = 0;
			
			// aapt resource value: 1
			public const int CircleButton_cb_pressedRingWidth = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
