#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Phoneword.Resource", IsApplication=true)]

namespace Phoneword
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int AlphaButton = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int ExclamButton = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int Mystery = 2131034118;
			
			// aapt resource value: 0x7f050006
			public const int ExclamButton = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int Mystery = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int PhoneNumberText = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int TranslateButton = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int TranslatedPhoneWord = 2131034120;
			
<<<<<<< HEAD
			// aapt resource value: 0x7f050004
			public const int gridLayout2 = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int keepButton = 2131034114;
			
=======
			// aapt resource value: 0x7f050007
			public const int button3 = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int gridLayout2 = 2131034115;
			
>>>>>>> a1c27dd8211fcd71a68ce5225832624d474f9104
			// aapt resource value: 0x7f050000
			public const int textView1 = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
