#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Calculator.Resource", IsApplication=true)]

namespace Calculator
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int MainPageLayout = 2131034112;
			
			// aapt resource value: 0x7f050010
			public const int calcButton0 = 2131034128;
			
			// aapt resource value: 0x7f05000c
			public const int calcButton1 = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int calcButton2 = 2131034125;
			
			// aapt resource value: 0x7f050008
			public const int calcButton4 = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int calcButton5 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int calcButton6 = 2131034122;
			
			// aapt resource value: 0x7f050005
			public const int calcButton7 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int calcButton8 = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int calcButtonClear = 2131034114;
			
			// aapt resource value: 0x7f050011
			public const int calcButtonDecimal = 2131034129;
			
			// aapt resource value: 0x7f050003
			public const int calcButtonDelete = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int calcButtonDivide = 2131034116;
			
			// aapt resource value: 0x7f050012
			public const int calcButtonEqual = 2131034130;
			
			// aapt resource value: 0x7f05000f
			public const int calcButtonInvert = 2131034127;
			
			// aapt resource value: 0x7f05000b
			public const int calcButtonMinus = 2131034123;
			
			// aapt resource value: 0x7f050007
			public const int calcButtonMultiply = 2131034119;
			
			// aapt resource value: 0x7f05000e
			public const int calcButtonPlus = 2131034126;
			
			// aapt resource value: 0x7f050001
			public const int calculatorAccumulator = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int calculator_number = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int calculator_operation = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int calculator_row = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
